### ISSUE TITLE
Activation setting missing within Settings

### ISSUE THREAD

**Issue by catxyz** [MrGlockenspiel/activate-linux#1]
It's missing.
Please add it immediately as I want to activate my Linux installation.

Also, a price list would be nice for each edition of Linux.

Thank you.

**Comment by MrGlockenspiel** [comment]
Did you properly install the Microsoft Windows Settings App?

As for pricing, you’ll have to ask the creators

**Comment by nightlyonie** [comment]
(sorry for the commit accident, I actually wanted to shorten the way of writing down the number of my README's update count - seems like GitHub uses # to reference issues, even from forked repositories...)

**Comment by MrGlockenspiel** [comment]
all good
