### ISSUE TITLE
Failed to compile on Fedora

### ISSUE THREAD

**Issue by CedMIX-Productions** [MrGlockenspiel/activate-linux#101]
What are the necessary dependencies for Fedora? DNF cannot find these packages (see DNF output below):

No match for argument: libcairo2-dev 
No match for argument: libxi-dev
No match for argument: libx11-dev
No match for argument: x11proto-core-dev
No match for argument: x11proto-dev
No match for argument: libxt-dev
No match for argument: libxfixes-dev
No match for argument: libxinerama-dev
Error : Unable to find a match: libcairo2-dev libxi-dev libx11-dev x11proto-core-dev x11proto-dev libxt-dev libxfixes-dev libxinerama-dev

And in the end, the build failed because of those missing dependencies and outputs something like this:

bash-5.1$ make
Package x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing 'x11.pc' to the PKG_CONFIG_PATH environment variable
Package 'x11', required by 'virtual:world', not found
Package 'xfixes', required by 'virtual:world', not found
Package 'xinerama', required by 'virtual:world', not found
Package cairo was not found in the pkg-config search path.
Perhaps you should add the directory containing cairo.pc' to the PKG_CONFIG_PATH environment variable
Package 'cairo', required by 'virtual:world', not found
cc src/activate_linux.c src/color.c -o activate-linux -Og -Wall -Wpedantic -Wextra  
src/activate_linux.c:6:10: fatal error: X11/Xlib.h: No such file or directory
    6 | #include <X11/Xlib.h>
      |          ^~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:28: activate-linux] Error 1

**Comment by ReperakDev** [comment]
Install the appropriate packages for your distribution

**Comment by MrGlockenspiel** [comment]
On fedora the packages you need are:
`libX11-devel`
`libXfixes-devel`
`libXinerama-devel`
`cairo-devel`

Works on my fedora machine
