### ISSUE TITLE
Black rectangle when compositing wm is not running

### ISSUE THREAD

**Issue by vrza** [MrGlockenspiel/activate-linux#109]
Perhaps the program should try to detect if compositing is not available, and gracefully degrade to pseudo-transparency, i.e. showing the watermark over root window only (program window always on bottom, its background copied from part of root window it's over).

**Comment by MrGlockenspiel** [comment]
I'm not sure how to go about copying from the root window, but a compositor check with a warning is definitely planned as I get asked about that a lot

**Comment by MrGlockenspiel** [comment]
Just added a warning if no EWMH compliant compositor is detected running in the latest commit

**Comment by vrza** [comment]
Thanks, I tested and the warning does appear. With regard to getting the root window pixmap, take a look at [how Eterm does it](https://github.com/mej/Eterm/blob/master/src/pixmap.c) in order to create a "fake transparency" effect.

**Comment by trigg** [comment]
Sorry, sticking my nose in. It's also possible to use XShape extension to toggle individual pixels as transparent, can't manage semi-transparency this way but could still draw over other windows without a compositor

**Comment by ohno9119** [comment]
I think we can close this now.
