### ISSUE TITLE
rewrite in rust

### ISSUE THREAD

**Issue by zemlyak-l** [MrGlockenspiel/activate-linux#113]
:rocket:

**Comment by ReperakDev** [comment]
We should rewrite in V or Hare
They are some of the languages of all time

**Comment by Stereo528** [comment]
Haskell when

**Comment by MrGlockenspiel** [comment]
We do not speak of h*skell

**Comment by ReperakDev** [comment]
>be me
>running haskell code in prod
>garbage collector goes off
>the binary gets deleted
mfw

**Comment by Ruby-Dragon** [comment]
no
