### ISSUE TITLE
Doesn't play nice with compositor-level blur

### ISSUE THREAD

**Issue by alba4k** [MrGlockenspiel/activate-linux#116]
Any easy way to exclude it from being blurred (picom)?

I'm referring to [this](https://i.imgur.com/2MdalEC.png)

**Comment by MrGlockenspiel** [comment]
Try running with the `-w` flag

**Comment by MrGlockenspiel** [comment]
If you add this to your picom.conf it should blacklist the blur effect on it
```
shadow-exclude = [
  "class_g ?= 'activate-linux'",
];
```

**Comment by alba4k** [comment]
Yup, that works, thanks a lot

Good luck with the continuation of your project, by the way
