### ISSUE TITLE
X11: Doesn't redraw after monitor wake-up

### ISSUE THREAD

**Issue by ahmubashshir** [MrGlockenspiel/activate-linux#129]
### Steps to reproduce:
1. Run this
2. Run `xset dpms force off` ; this puts active monitor to sleep.
3. Wake up monitor by moving mouse/pressing keyboard...

### Expected behavior
The watermark should be visible.

### What happens
The watermark disappears.

---
https://user-images.githubusercontent.com/24864366/179542670-b28db1b8-b706-4bf1-b106-4ccb1b36441d.mp4

**Comment by AHOHNMYC** [comment]
#58
