### ISSUE TITLE
yo mama

### ISSUE THREAD

**Issue by Snivyer1910** [MrGlockenspiel/activate-linux#13]
no u

**Comment by Z-8Bit** [comment]
thicc

**Comment by ZtereoHYPE** [comment]
Closed for spam. Please don’t shitpost on the issue tracker.

**Comment by Snivyer1910** [comment]
> Closed for spam. Please don’t shitpost on the issue tracker.

I'd rather spam my penis in yo mama

**Comment by TheAwesome98-Real** [comment]
> > Closed for spam. Please don’t shitpost on the issue tracker.
> 
> I'd rather spam my penis in yo mama

Based
