### ISSUE TITLE
Can't open "wl_registry@2: error 0: invalid version for global wl_output (44): have 3, wanted 4"

### ISSUE THREAD

**Issue by Techwizz-somboo** [MrGlockenspiel/activate-linux#130]
`wl_registry@2: error 0: invalid version for global wl_output (44): have 3, wanted 4`

Using Fedora 36 on Wayland with Plasma.

**Comment by Nefsen402** [comment]
#128 adds a commit to fix this.

**Comment by Techwizz-somboo** [comment]
Nice! Thanks
