### ISSUE TITLE
[feature request] Portable versions

### ISSUE THREAD

**Issue by FalsePhilosopher** [MrGlockenspiel/activate-linux#136]
Is there any way to package this project in to a portable executable like an app image? It has great rubber ducky prank potential if you could nohup an app image to tmp and launch it or hide it in their home folder and have a cronjob run it @reboot for persistence.

**Comment by Ruby-Dragon** [comment]
if you build it with make, then you can put the executable wherever you like.

**Comment by FalsePhilosopher** [comment]
@Ruby-Dragon that doesn't install the dependencies required by this. An appimage packages all the required libraries, so it's one click execute. No installing dependencies or building it, you just chmod +x && ./ and boom activate linux watermark.

**Comment by Ruby-Dragon** [comment]
Oh okay I see what you mean.

**Comment by FalsePhilosopher** [comment]
@Ruby-Dragon It's somewhat easy to package appimages, you need to spin up a 18.04 ubuntu vm as that's the oldest supported ubuntu distro to ensure the appimage works on all supported ubuntu distros. Setup your app dir and required files like .desktop, icon, runfile, and use linuxdeployqt or linuxdeploy to package the libraries and executable into an appimage.

**Comment by FalsePhilosopher** [comment]
Also this runs under WSL for extra lulz. You just don't get the transparency effect behind the text.

**Comment by MrGlockenspiel** [comment]
just added in the latest commit :+1: 

you can build them with `make appimage`

**Comment by FalsePhilosopher** [comment]
> just added in the latest commit +1
> 
> you can build them with `make appimage`

Much love you mad lad!
Here's that ducky script I was talking about writing https://github.com/FalsePhilosopher/BadUSB-Playground/blob/main/Ducky/USBRubberducky/library/prank/Unix-like/Linux/Activate_linux/quack.txt

**Comment by FalsePhilosopher** [comment]
> just added in the latest commit +1
> 
> you can build them with `make appimage`

Much love you mad lad!
Here's that ducky script I was talking about writing https://github.com/FalsePhilosopher/BadUSB-Playground/blob/main/Ducky/USBRubberducky/library/prank/Unix-like/Linux/Activate_linux/quack.txt
