### ISSUE TITLE
This is a waste of time.

### ISSUE THREAD

**Issue by coolio321** [MrGlockenspiel/activate-linux#138]
Spend your time better.

**Comment by AHOHNMYC** [comment]
Y u so serious? You didn't activated your Linux, did you?

**Comment by MrGlockenspiel** [comment]
virgin cancer researcher vs chad activator of linux

**Comment by InFTord** [comment]
ok mr uncoolio321

**Comment by Naamloos** [comment]
Imagine paying for Linux. Big L.

**Comment by bayuah** [comment]
Well, Linux itself is free, but certain distributions need you pay certain money to its certain services, for example Red Hat.

**Comment by Ghibranalj** [comment]
And you're here wasting your time creating an issue.

**Comment by iQuickDev** [comment]
> Spend your time better.

big L man

**Comment by mutexdeveloper** [comment]
sounds like something a activated linux user would say!

**Comment by Slackadays** [comment]
How much did you pay for your Linux Pro Premium Plus Gold Edition key?

**Comment by coolio321** [comment]
Thank you to @Pnislovr99 for the support.
