### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by Ruby-Dragon** [MrGlockenspiel/activate-linux#140]
add support for French and Spanish (maybe a few others as well)

i'll probably do this later

**Comment by AHOHNMYC** [comment]
If you are native speaker, this is one line per language in
https://github.com/MrGlockenspiel/activate-linux/blob/main/src/i18n.c#L13
Editing can be done using only GitHub site in two minutes.

And why these two languages only? 👁️👁️‍🗨️

**Comment by Ruby-Dragon** [comment]
I know how to add it, and no you can't just add it in the site, you need to make sure you didnt mess anything up and that it is still working.

the reason for those two languages is because I know people who speak them, and will be able to verify that the translation is correct.
