### ISSUE TITLE
[Question] WSL support

### ISSUE THREAD

**Issue by Naamloos** [MrGlockenspiel/activate-linux#144]
Hello there,

I was wondering if this would run under WSL? I activated my windows so it lost all it's swag.

Thank you

**Comment by BeautyYuYanli** [comment]
You may have a try if you have the WSL environment, though I think using Windows API to port a Win version is a better idea.

**Comment by MrGlockenspiel** [comment]
i believe @WoMspace got this working through WSLg at one point

**Comment by Ruby-Dragon** [comment]
iirc it does not have a transparent background. Native windows support could be added in the future but it is not intended to be used under windows right now

**Comment by Naamloos** [comment]
ah man ah darn it (I wonder if there's any way to reactivate the native popup without deactivating my windows)

**Comment by Ruby-Dragon** [comment]
this now support Windows natively so this issue may no longer be need
