### ISSUE TITLE
20 activate-linux stack. The text increases in brightness after each instance.

### ISSUE THREAD

**Issue by Smotherly** [MrGlockenspiel/activate-linux#159]
![Screenshot from 2022-10-20 16-48-18](https://user-images.githubusercontent.com/111497717/196902351-9bb63c0b-3e48-4d0d-85c6-3f07758ba1fd.png)

Could this be the best bug or the worst feature?

**Comment by SapphicSapphire** [comment]
what happens when you open thousands of it at once

**Comment by MrGlockenspiel** [comment]
Its not a bug or feature, its just what happens when you have multiple translucent things on top of each other lol

**Comment by Ruby-Dragon** [comment]
as @MrGlockenspiel said, this is just how translucency works, this can be closed now
