### ISSUE TITLE
NodeJS Support

### ISSUE THREAD

**Issue by ethanrettinger** [MrGlockenspiel/activate-linux#166]
Rewrite it in node and make it a service, bundled with `pkg`. It'll be 4.4 x 4^4^4^4^4 (Four point four morbillion) times faster.

```mermaid
graph TD;
    A[Activate Linux] --> B{Runtime environment?};

    B --> C[bun.sh];
    B --> D[runtime.js unikernal];
    B --> E[node];
    B --> F[deno];
```

🙏🏼

**Comment by MrGlockenspiel** [comment]
When im in a god fucking awful idea competition and my opponent is ethan rettinger

**Comment by CephalonCosmic** [comment]
@BluSpring wanna do something cursed?

**Comment by ethanrettinger** [comment]
> When im in a god fucking awful idea competition and my opponent is ethan rettinger

Racially motivated gart moment
