### ISSUE TITLE
where do i buy linux pro plus premium edition

### ISSUE THREAD

**Issue by victoriaquasar** [MrGlockenspiel/activate-linux#174]
buy links are not working see you in the court mr glockenasisneptielel

**Comment by AHOHNMYC** [comment]
@MrGlockenspiel our human society absolutely have to produce some license to this product. And keygen. Which have to be included in activate-linux distribution. And detailed instruction in man file how to use official keygen.

**Comment by sh4dowb** [comment]
FKCGW-...

**Comment by Ruby-Dragon** [comment]
just put your credit card number here and we will fix that for you :)

**Comment by ethanrjs** [comment]
https://archlinuxcdkeys.com
