### ISSUE TITLE
Disappointed that activate-linux for windows doesnt say "activate linux"

### ISSUE THREAD

**Issue by Chad90b** [MrGlockenspiel/activate-linux#179]
As title suggests it would be preferable if the windows edition also read "Activate Linux".

Thank you

**Comment by AHOHNMYC** [comment]
@Chad90b first: to activate Linux you have to have Linux.
Second: just run your legal copy of application <s>like Chad</s> like this: `activate-windows.exe -p linuxxx`.
- Or like this `activate-linux.ex -t "Activate Leenouix"`.
- Or open exe with your favorite text editor, replace strong "ween-dows" with "leenoux   " (spaces in the end matters. Replacement must have same length as original. This spaces are for demonstration only. Does not try to copy and use this. Calculate them for yourself).
- Or write loader to run this exe with already activated `linux` preset
- Or hack WinAPI `DrawTextW` from USER32.DLL that is used for writing text on Device Context. Wrap hack in GUI application and sell for money. Implement this as kernel driver
- Or send patch to ReactOS that does same with `DrawTextW`, wait <s>for laugh</s> until it will be merged, pretend it was originally intended
