### ISSUE TITLE
How to activate linux?

### ISSUE THREAD

**Issue by davidak** [MrGlockenspiel/activate-linux#185]
So i have this "activate linux" watermark on my screen and it's very annoying, especially in games.

![Screenshot from 2023-08-16 20-33-45](https://github.com/MrGlockenspiel/activate-linux/assets/91113/215db14c-9540-4459-80a1-ab1ec0eb16bd)

I don't really understand how it is supposed to work. Do i need a key or something? I don't really can afford an activation key right now, but i want to keep using this system. Could there be a keygen? Maybe someone is creative and can solve this.

**Comment by MrGlockenspiel** [comment]
yup

**Comment by AnthonyHerman** [comment]
Ask chatGPT to generate you some keys.
