### ISSUE TITLE
SEGFAULT when LANG variable is not set

### ISSUE THREAD

**Issue by toiletflusher** [MrGlockenspiel/activate-linux#187]
I was compiling activate-linux on my secondary laptop and it gave me a "Segmentation fault". I ran it through GDB and it says something related about locales:
![image](https://github.com/MrGlockenspiel/activate-linux/assets/80153347/704b681d-b2f5-4851-8fa3-7b6c00802e25)
If you set it to a random string, no string or a valid language it doesn't SEGFAULT.

**Comment by MrGlockenspiel** [comment]
should be fixed now, thanks
