### ISSUE TITLE
"Unable to locate package" on Ubuntu 23.04

### ISSUE THREAD

**Issue by KaKi87** [MrGlockenspiel/activate-linux#189]
Hi,

After adding the PPA and running `apt update`, Ubuntu 23.04 says the package still doesn't exist :

> E: Unable to locate package activate-linux

Thanks

**Comment by MrGlockenspiel** [comment]
@eddelbuettel runs the PPA, I have no control over it
I'd suggest just building from source if it doesn't work

**Comment by eddelbuettel** [comment]
@KaKi87 I once built an older version, and only built it for distribution releases available then. The PPA show you that; however you can / should be able to add an older distro release via a PPA to you current system.  I am running 23.10 myself and I freely with a number of third party repostiories.  In general "older release works" because of forward compatibility.

**Comment by KaKi87** [comment]
How about binary releases for Linux ? Thanks

**Comment by KaKi87** [comment]
> you can / should be able to add an older distro release via a PPA to you current system

What do you mean ?

**Comment by eddelbuettel** [comment]
@KaKi87 In fact it _is_ right there:

![image](https://github.com/MrGlockenspiel/activate-linux/assets/673121/803cf336-cea0-4ecb-b50f-fe443811ee10)

So if you just pick _jammy_ aka 22.04 as the distro of the PPA you are golden. 

Follow the instructions:

![image](https://github.com/MrGlockenspiel/activate-linux/assets/673121/79052e1d-aa6b-4d52-81b2-1f0b86710680)

which, once you pick 'jammy' become even clearer

![image](https://github.com/MrGlockenspiel/activate-linux/assets/673121/ff2f3ba6-40aa-4389-9b56-ca0ff84e4fa3)

As usual, you do not (generally) need the source deb indicate on the `deb-src` line.  Just pick the previous one.  There is your binary.

**Comment by KaKi87** [comment]
That worked, thanks. It would still be nice to make the latest distros point transparently to the same file, or at least explain in the README that "jammy" must be used. Thanks
