### ISSUE TITLE
Language Override

### ISSUE THREAD

**Issue by Ruby-Dragon** [MrGlockenspiel/activate-linux#195]
If I want my watermark to be in German, but I don't want my system language to be in German, the only option right now is to manually add the German translation in as the Title and Subtitle. To solve this problem, I propose that a language override is added to allow the user to specify what language should be used. I am attempting to implement it right now, but the current setup for i18n makes this kind of a pain.

**Comment by MrGlockenspiel** [comment]
you should be able to use env variables to override it, i.e. `LANG=de_DE.utf8 activate-linux`

**Comment by Ruby-Dragon** [comment]
Interestingly, trying with fr_FR works, but de_DE does not

**Comment by MrGlockenspiel** [comment]
both seem to work fine for me

**Comment by Ruby-Dragon** [comment]
strange. Still, I think that allowing the language to be overridden may be helpful as it may make it easier for people to change the language without having to figure out the env variable trick.

**Comment by Ruby-Dragon** [comment]
Can somebody please test my code here and maybe find why it isn't working https://github.com/Ruby-Dragon/activate-linux/tree/langoverride ? The error is coming from the Wayland code, but I have not changed ANYTHING even close to that. This should allow the user to override their system language with the -o flag, but it gives this error instead: zwlr_layer_surface_v1@9: error 1: the layer surface has a width of 0 but its anchor doesn't include the left and the right screen edge.
