### ISSUE TITLE
fails to compile on windows

### ISSUE THREAD

**Issue by xeome** [MrGlockenspiel/activate-linux#2]
why

**Comment by MrGlockenspiel** [comment]
try putting your computer in a bag of rice

**Comment by Jocadbz** [comment]
Based

**Comment by MrCheeze446** [comment]
have you trilled installing linux?

**Comment by ThePonySlay** [comment]
try to install gentoo, it works all the time and it's very easy

**Comment by LizAinslie** [comment]
Use LFS it's faster

**Comment by Jocadbz** [comment]
> Use LFS it's faster

I agree

**Comment by codingMASTER398** [comment]
> try putting your computer in a bag of rice

I try still cant get on widnows!! You are a this lair and deceptive.i will call cop if no fixx! Compute fill with rice!!??!!??!@(&;&/$

**Comment by quisys** [comment]
> Based

nice pfp brother

**Comment by Jocadbz** [comment]
> > Based
> 
> nice pfp brother

Oh, another floppa brother

**Comment by NotCoolKiwi** [comment]
> > Use LFS it's faster
> 
> 
> 
> I agree
> 
> 

I agree

**Comment by MrGlockenspiel** [comment]
clearing out issue clutter
