### ISSUE TITLE
[RFE] Fall back to matching two-letter language code

### ISSUE THREAD

**Issue by MarcelWaldvogel** [MrGlockenspiel/activate-linux#202]
*Problems:*

1. My system language is `de_CH`, but only `de_DE` is listed among the supported languages. So it falls back to using the English version instead of the closer `de_DE`. (Yes, `de_CH` could be added to the list of supported languages, but also see the next item)
2. Some languages have a long list of country codes. E.g. Spanish has some 18 countries listed (and the list probably still is not complete)

*Proposal:*

1. Do the current 5-character match (language+country)
2. If there is no 5-character match, try with a two-character match (language)
3. If there is no two-character match either, fall back to the default language

This would result in a more appropriate language being chosen.

**Comment by Ruby-Dragon** [comment]
seems like this should be straightforward enough
