### ISSUE TITLE
how 2 get covid 19 ez

### ISSUE THREAD

**Issue by insomnia-creator** [MrGlockenspiel/activate-linux#21]
step uno: go to airport
step 2: remove mask
step 3: not wash hands
step 4: hug ppl
step 5: eat food in crowded restaurant
step 6: sit on flying container without mask

**Comment by Saraistupid** [comment]
instructions failed, got covid 22 instead

**Comment by NotCoolKiwi** [comment]
Life speedrun any %

**Comment by insomnia-creator** [comment]
> instructions failed, got covid 22 instead

u forgor to eat food in crowded restaurant 💀

what use is remov mask if not go eat at crowded restaurant

**Comment by insomnia-creator** [comment]
> > > instructions failed, got covid 22 instead
> > 
> > 
> > u forgor to eat food in crowded restaurant 💀
> > what use is remov mask if not go eat at crowded restaurant
> 
> I did all of these steps completely and perfectly, even got a friend to try, if does not work.

u didnt go to airport stupid, u need to eat AT airport fool

**Comment by Saraistupid** [comment]
> > > > instructions failed, got covid 22 instead
> > > 
> > > 
> > > u forgor to eat food in crowded restaurant skull
> > > what use is remov mask if not go eat at crowded restaurant
> > 
> > 
> > I did all of these steps completely and perfectly, even got a friend to try, if does not work.
> 
> u didnt go to airport stupid, u need to eat AT airport fool

 I have gone to an airport.

**Comment by insomnia-creator** [comment]
> > > > > instructions failed, got covid 22 instead
> > > > 
> > > > 
> > > > u forgor to eat food in crowded restaurant skull
> > > > what use is remov mask if not go eat at crowded restaurant
> > > 
> > > 
> > > I did all of these steps completely and perfectly, even got a friend to try, if does not work.
> > 
> > 
> > u didnt go to airport stupid, u need to eat AT airport fool
> 
> I have gone to an airport.

bruh

U DIDNT EVEN REMOVE UR MASK WHAT IS THIS

**Comment by Saraistupid** [comment]
> > > > > > > > instructions failed, got covid 22 instead
> > > > > > > 
> > > > > > > 
> > > > > > > u forgor to eat food in crowded restaurant skull
> > > > > > > what use is remov mask if not go eat at crowded restaurant
> > > > > > 
> > > > > > 
> > > > > > I did all of these steps completely and perfectly, even got a friend to try, if does not work.
> > > > > 
> > > > > 
> > > > > u didnt go to airport stupid, u need to eat AT airport fool
> > > > 
> > > > 
> > > > I have gone to an airport.
> > > 
> > > 
> > > bruh
> > > U DIDNT EVEN REMOVE UR MASK WHAT IS THIS
> > 
> > 
> > I removed it and pissed on it Infront if everyone
> 
> lol u are mistakin so much
> 
> i check airport camera, YOU FORGOR TO HUG PPL STUPOD

this is too much quotes, anyways, you checked old records, i hugged everyone i saw, even the security, i'm in jail now.

**Comment by insomnia-creator** [comment]
> > > > > > > > > instructions failed, got covid 22 instead
> > > > > > > > 
> > > > > > > > 
> > > > > > > > u forgor to eat food in crowded restaurant skull
> > > > > > > > what use is remov mask if not go eat at crowded restaurant
> > > > > > > 
> > > > > > > 
> > > > > > > I did all of these steps completely and perfectly, even got a friend to try, if does not work.
> > > > > > 
> > > > > > 
> > > > > > u didnt go to airport stupid, u need to eat AT airport fool
> > > > > 
> > > > > 
> > > > > I have gone to an airport.
> > > > 
> > > > 
> > > > bruh
> > > > U DIDNT EVEN REMOVE UR MASK WHAT IS THIS
> > > 
> > > 
> > > I removed it and pissed on it Infront if everyone
> > 
> > 
> > lol u are mistakin so much
> > i check airport camera, YOU FORGOR TO HUG PPL STUPOD
> 
> this is too much quotes, anyways, you checked old records, i hugged everyone i saw, even the security, i'm in jail now.

we got your covid report back

you're positive

IT WORSKSSSSS

**Comment by MrGlockenspiel** [comment]
clearing out issue clutter
