### ISSUE TITLE
it dont work Multi bomontiro

### ISSUE THREAD

**Issue by wael444** [MrGlockenspiel/activate-linux#22]
it dont work
![image](https://user-images.githubusercontent.com/47404953/161823997-19c9278d-526a-4962-ae12-19bd1f451ae5.png)
where is my Activate Linux
Where is my activate linux

Add multimonitor support plz.........,,

**Comment by AradiaIsStupid** [comment]
![image](https://user-images.githubusercontent.com/75750909/161824880-4ec4cefd-9af4-474b-baee-038b2839d4fc.png)

**Comment by Midou36O** [comment]
still too small, can you enhance it even more?

**Comment by wael444** [comment]
Xinerama

**Comment by MrGlockenspiel** [comment]
fixed in commit a446f9b

**Comment by wael444** [comment]
holy shit it actually works
![image](https://user-images.githubusercontent.com/47404953/162799185-52da7f8a-9ca2-4f6a-8c3e-0faab15bf423.png)
thank youz

**Comment by MrGlockenspiel** [comment]
no problem
~~im as surprised as you are that it worked~~

**Comment by wael444** [comment]
this is why you should wait on the original issue's original poster to see if the thing actually works first incase it shitted itself

**Comment by MrGlockenspiel** [comment]
this is true
