### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by itspngu** [MrGlockenspiel/activate-linux#26]
Hey I'd love to activate my Linux but I'm using Wayland. Is this being worked on?

**Comment by MrGlockenspiel** [comment]
I've heard it works through XWayland out of the box, but haven't done any testing of my own
I'd like to support as much as possible, but using Xlib kind of limits that without requiring a complete rewrite

**Comment by 10maurycy10** [comment]
Works with XWayland for me

**Comment by Kljunas2** [comment]
I created a [wayland version of this project](https://github.com/Kljunas2/activate-linux).
