### ISSUE TITLE
Bug or feature?

### ISSUE THREAD

**Issue by OhaDerErste** [MrGlockenspiel/activate-linux#3]
I don't want to turn my pc into a room heater.
(Represents Windows ressource usage very accurate)

**Comment by OhaDerErste** [comment]
Is this a Feature???

**Comment by MrGlockenspiel** [comment]
Feature
~~100% not an oversight that im going to fix~~

**Comment by OhaDerErste** [comment]
Could you also port Ram usage?

**Comment by MrGlockenspiel** [comment]
My bad I must have forgotten the `malloc(400000);`

**Comment by MrGlockenspiel** [comment]
ok this is actually fixed now
in retrospect i shouldnt have missed that disaster
