### ISSUE TITLE
Shows black background on macOS

### ISSUE THREAD

**Issue by Cake967** [MrGlockenspiel/activate-linux#31]
I could install it on macOS, but it has a black background:
![image](https://user-images.githubusercontent.com/80169337/162626669-4f71debc-9851-4344-a691-900ee2d39b89.png)

**Comment by MrGlockenspiel** [comment]
Yes
Unfortunately XQuartz does not support transparency so theres not anything I can do about that at the moment
There might be a nasty hack somewhere or something though to fix it

**Comment by MrGlockenspiel** [comment]
im gonna close this now, any stuff related to macOS support can go to issue #9
