### ISSUE TITLE
HiDPI support

### ISSUE THREAD

**Issue by alexamy** [MrGlockenspiel/activate-linux#35]
Hi! Are you planning to add hidpi support?

**Actual**
There is no HiDPI support, the label is small and **didnt provide authentic windows experience**.
See screenshot below.

**Expected**
The label is scaled according to interface scale factor of the system.

**Configuration**
```
❯ lsb_release -a
LSB Version:    n/a
Distributor ID: Arch
Description:    Arch Linux
Release:        rolling
Codename:       n/a

❯ plasmashell --version
plasmashell 5.24.4
                                                                                                                                                                                                 
❯ kf5-config --version
Qt: 5.15.3
KDE Frameworks: 5.93.0
kf5-config: 1.0
```

**Screenshot**
![Screenshot_20220416_082556](https://user-images.githubusercontent.com/596195/163662851-9e480bfc-a571-44a9-85a0-079d96ba8094.png)

**Display settings**
![image](https://user-images.githubusercontent.com/596195/163662952-edff8239-ed01-41e4-9a8d-b20f6c1da06c.png)

**Comment by Ruby-Dragon** [comment]
high DPI support is already supported using the scale feature. Read ARGS.md for more information.

**Comment by Ruby-Dragon** [comment]
![image](https://user-images.githubusercontent.com/91497228/163838351-f8e9da0a-df12-4f12-9200-e52e39e15f93.png)

**Comment by Ruby-Dragon** [comment]
@MrGlockenspiel please close this issue

**Comment by MrGlockenspiel** [comment]
might add automatic scaling eventually, but it'll be a while

**Comment by Cryolitia** [comment]
> high DPI support is already supported using the scale feature. Read ARGS.md for more information.

Could we use different DPI for each monitor? For example, I would like to use 200% scale on my 2160p 15.6inch monitor and 100% scale on my 1080p monitor.

**Comment by Ruby-Dragon** [comment]
It appears that auto-scaling under Wayland does that already, but I don't think you can specify which displays you want to scale when using manual scaling.
