### ISSUE TITLE
omg how do i get rid of it help its taking all my cpu

### ISSUE THREAD

**Issue by Arkhtek** [MrGlockenspiel/activate-linux#4]

**Comment by MrGlockenspiel** [comment]
I already fixed that

**Comment by Arkhtek** [comment]
just updated it works now

**Comment by ThePonySlay** [comment]
it was working like Windows 10, using all your cpu because you buyed the whole pc to use it

**Comment by RedsonBr140** [comment]
> it was working like Windows 10, using all your cpu because you buyed the whole pc to use it

I just buyed a Positivo Motion Q232A, it's not working fine with windows 11 :sob: what i can do?

**Comment by Snivyer1910** [comment]
> > it was working like Windows 10, using all your cpu because you buyed the whole pc to use it
> 
> I just buyed a Positivo Motion Q232A, it's not working fine with windows 11 😭 what i can do?

though I had a potato
