### ISSUE TITLE
Transparency broken

### ISSUE THREAD

**Issue by GauntletWizard** [MrGlockenspiel/activate-linux#42]
On my Arch machine, the text shows up on a black box:
![image](https://user-images.githubusercontent.com/194325/168486775-c25c7739-e2cf-461c-8f69-3dc5c5b3f2e8.png)
Here's the xwininfo:
```
xwininfo: Window id: 0x1000006 "ted@suki:~/code/activate-linux"

  Absolute upper-left X:  3
  Absolute upper-left Y:  34
  Relative upper-left X:  3
  Relative upper-left Y:  0
  Width: 2250
  Height: 1429
  Depth: 24
  Visual: 0x3cb
  Visual Class: TrueColor
  Border width: 0
  Class: InputOutput
  Colormap: 0x1000005 (not installed)
  Bit Gravity State: NorthWestGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: no
  Corners:  +3+34  -3+34  -3-41  +3-41
  -geometry 148x38+0+34
```

Happy to provide any more debugging info.

**Comment by 9p4** [comment]
Do you have a compositor installed?

https://github.com/MrGlockenspiel/activate-linux/issues/37

**Comment by koutsie** [comment]
Seems like you don't have a compositor?
Perhaps something like "picom" would work for you?

**Comment by GauntletWizard** [comment]
That was it, running picom worked.
