### ISSUE TITLE
🤬🤬What have you done to my computer?🤬🤬 

### ISSUE THREAD

**Issue by kskeigrshi** [MrGlockenspiel/activate-linux#50]
I'm trembling with fear. I CANNOT BELIEVE WHAT HAPPENED TO MY ABSOLUTELY PROPRIETARY LINCUCKS SYSTEM! I've been fighting my whole life for lincucks, and the result I get for all the effort is this? Linyov Torovoltovich, that Soviet evil Russian backstabber! That bastard finally added a BACK DOOR and ACTIVATION SYSTEM on my LINCUCKS SYSTEM!!!!!!!😠😠😠😠🤬🤬🤬🤬🤬 FREE MURICA!!! We Muricans don't deserve this treatment! The 'mp3' program must finally be damaging my computer!🤬🤬🤬

**Comment by brennschlus** [comment]
I was at zoom call and my boss saw this watermark and he was like why did you not buy loicence? Am I pay you not enough for stupid licence or maybe you do drugs? I was so shocked so I can't even reply! Later HR is wrote me in Slack what I was fired. AND HOW I AM SUPPOSED TO BUY DRUGS NOW WITHOUT MONEY?

**Comment by MrGlockenspiel** [comment]
L
