### ISSUE TITLE
Hide if any app fullscreen

### ISSUE THREAD

**Issue by maramowicz** [MrGlockenspiel/activate-linux#51]
Its funny have "Activate Linux" on screen, but sometimes someone can not want it, for example if we watching video or gaming on fullscreen. So its would be nice if we have "Hide If Any App Fullscreen" option (or shorter "HIAAF" :).
Of course we can just close aplication... but we must run it again if we want it back.

**Comment by kskeigrshi** [comment]
Malware must be intrusive at all times. Haven't you learned from the Windows days?

**Comment by maramowicz** [comment]
Yes but you see, this is not a malware (if yes why we can turn it off?). And I know, this "simulate" malware but someone (like me) can want to have this in little "gentler" version.

**Comment by MrGlockenspiel** [comment]
No you need the Full Windows Experience:tm: at all times

**Comment by kommersch** [comment]
Just activate Linux, Jesus.

**Comment by maramowicz** [comment]
Ok understandable, have a nice day.
