### ISSUE TITLE
error message for MacOs users seems incorrect

### ISSUE THREAD

**Issue by MikeHingley22** [MrGlockenspiel/activate-linux#53]
just reading through the source code - I'm not a C developer - but this project seemed small enough for me to understand.

Just above this line : 
https://github.com/MrGlockenspiel/activate-linux/blob/827e5ee5f53c617155a9cc7059fc8f9e55b0cddd/src/activate_linux.c#L166

we set the colour bit depth to 24bit for MacOS users - however the error message specifies 32bit.

this error message should probably specify the bit depth that is being passed in.

**Comment by MrGlockenspiel** [comment]
yeah ill probably fix that soon
