### ISSUE TITLE
Feature: Unlock

### ISSUE THREAD

**Issue by ManInDark** [MrGlockenspiel/activate-linux#55]
Maybe add the feature that it won't show up for a specified time if there is a file (with user specific content) in the home directory which has to be gpg-signed by you. Maybe something like hostname-username-displayprogram-timestamp in ~/.activate-linux/unlock.gpg

**Comment by Ruby-Dragon** [comment]
So a way to activate linux?

**Comment by MrGlockenspiel** [comment]
Thats a bit complicated and outside the scope of this, normal human beings wont be running it 24/7 anyway lol
