### ISSUE TITLE
No line breaks in long messages

### ISSUE THREAD

**Issue by NetherQuartz** [MrGlockenspiel/activate-linux#57]
I wanted it to show the original message from Windows in Russian, which should look like this:
![image](https://user-images.githubusercontent.com/47905455/168663996-c2857357-daa0-40c5-957d-3066426ed54b.png)

But long lines just go out of screen with no breaks:
![image](https://user-images.githubusercontent.com/47905455/168664356-34cf45e2-80ba-4798-8510-5606e59cf064.png)

And I haven't found any ways to insert line breaks manually, they're always disappearing.

**Comment by NetherQuartz** [comment]
If I pass line break as `$'...\n...'`:
`./bin/activate-linux 'Активация Linux' $'Чтобы активировать Linux,\nперейдите в раздел "Параметры"'`,
`\n` is being replaced with a square:
![image](https://user-images.githubusercontent.com/47905455/168667023-a8afb20f-08b7-486c-afdf-16dcf4067a4b.png)

**Comment by Ruby-Dragon** [comment]
this is probably our highest priority issue rn

**Comment by MrGlockenspiel** [comment]
as much as i dont want to drag in another dependency, i might have to for this
https://lists.cairographics.org/archives/cairo/2008-September/015049.html

**Comment by Ruby-Dragon** [comment]
We could probably do it ourselves, it would just take a bit of effort

**Comment by ohno9119** [comment]
I managed to come up with a fix for this issue and #59. I'm waiting for the GPL3 PR to finalize before I can create a PR for it

**Comment by BeautyYuYanli** [comment]
https://github.com/MrGlockenspiel/activate-linux/blob/a5cbacea74f9550a86b1141a9f793e9c2d5ad340/src/activate_linux.c#L49

can we handle '\n' manually here?

**Comment by NetherQuartz** [comment]
It's probably possible to split the string by '\n' and draw a text box for each line

**Comment by BeautyYuYanli** [comment]
I've made a draft and it's the preview image
![image](https://user-images.githubusercontent.com/32453863/170498238-9a3b00c1-b54b-4ea0-bc44-90f40309aa2c.png)

**Comment by MrGlockenspiel** [comment]
fixed with #117
