### ISSUE TITLE
text disappears upon wake from sleep

### ISSUE THREAD

**Issue by trollogyadherent** [MrGlockenspiel/activate-linux#58]
I use `sudo echo mem > /sys/power/state` to put my laptop to sleep, upon wake up the window is still there (thanks picom shadow), but the text has vanished. I bet it's a deeper problem with some lib and ahem ahem novidia but who knows

**Comment by Ruby-Dragon** [comment]
I dont think that is something we can fix

**Comment by MrGlockenspiel** [comment]
Interesting 
I have no idea why it does that

**Comment by ReperakDev** [comment]
AMD GPU user here. Works for me under X.org. Seems like a Nvidia thing. Never been good with suspending.

**Comment by davidak** [comment]
I have the same issue.

Pantheon desktop on NixOS. AMD GPU
Can i do anything to help debug this?

**Comment by Ruby-Dragon** [comment]
I have not been able to replicate it with an AMD GPU (KDE on EndeavourOS)

**Comment by ahmubashshir** [comment]
Guys, try #134

![image](https://user-images.githubusercontent.com/24864366/180462158-7462dd43-e0ee-4af9-83bf-03532f402b56.png)

**Comment by ahmubashshir** [comment]
Does this still happen with #134?, if not, this can probably be closed :3
