### ISSUE TITLE
Windows and ReactOS support

### ISSUE THREAD

**Issue by gnarlin** [MrGlockenspiel/activate-linux#60]
Surely those poor (after paying for those Windows licenses) Windows users might miss that old friend, the watermark. I say, let them bring it back.

ReactOS users especially don't have this wonderful feature of not having their operating system that they paid dearly for (bandwidth isn't free after all) call upon them to activate. Might they not also like to enjoy this immensely cultural feature? Do have that classy watermark adorn their screens?

**Comment by Ruby-Dragon** [comment]
Bruh

**Comment by MrMelon54** [comment]
some people lol
just don't pay for windows if you want to watermark
