### ISSUE TITLE
update release

### ISSUE THREAD

**Issue by Ruby-Dragon** [MrGlockenspiel/activate-linux#66]
update release maybe every week? (maybe there is an automated way to do this?)

**Comment by the-maldridge** [comment]
Typically releases should only be cut when there is something to release.  The Void team requires packages to be in step with upstream released version numbers because we use this as an indicator that upstream has declared the package stable.

**Comment by MrGlockenspiel** [comment]
I'll make a new one with major changes, whether thats features or stability
