### ISSUE TITLE
this is a SCAM!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by 89mpxf** [MrGlockenspiel/activate-linux#7]
Ok guys, hear me out bcuz i am TRIGGERED!!! i was just minding my business in my redhat based arch linux distro and all of a sudden: AXTIVATE LINUX>??? on my screen!? what the crap??? so I went online to figure out how to frickin activate my linux and I COULD NOT FIND???????? what the heck is "open-source"??? last time i checked the source engine by Valve(tm) IS ALREADY OPEN? so i had to go to Like page 52 on google.com and I find "purcahse linux product key" so i clicked. and then it said $200??? kind of expensive but linux is cool and good so I was like ok i will pay to activate. but they didnt accept google pay what the heckkkkkk!!!!!!!! so i had to go ask for my DADS credit card. he said no bcuz he is a stupid idiot so i had to steal it from him while he was wrestling with mom. and i put card number into the site so i could activate my linux and get rid of this stupid messgae on screen and everything was ok. i pressed buy and then.. NO PRODUCT KEY APPEAR?????????? now my linux is not activated and my dad hits me every night and day. fuk u mrcockenspiel i hate u so much!!!!!!!!!!1 FUCK YOU SCAMMAR!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by MrGlockenspiel** [comment]
cope

**Comment by Arkhtek** [comment]
mald

**Comment by asoji** [comment]
seethe

**Comment by Stereo528** [comment]
weep

**Comment by Jocadbz** [comment]
lmao

**Comment by DonutDev** [comment]
i can't believe you did that, anyone with at least 10 IQ can figure out you need to hack NASA using the ping command to get rid of the Activate Linux thing, you need to redeem yourself for it

**Comment by Snivyer1910** [comment]
ratio

**Comment by Jocadbz** [comment]
Since this issue comments are just pure joke, I'm gonna leave mt recipe here.

**Steak with eggs**

Ingredients:
- Oil (any kind)
- Steak
- 3 eggs

Steps:
- Cut the steak into little pieces
- On a pan, add oil, let it heat and then drop the steak.
- While you wait, on a bowl, add the 3 eggs and mix them until you only see yellow color.
- When the steak is cooked, add the eggs, and mix them until the egg is cooked.
- Add salt 

Done!

**Comment by Arkhtek** [comment]
unironically the most helpful thing in this entire fucking thread

**Comment by MAKA02** [comment]
carding and loading is an act to be done by legitimate people 
need verification on how to get quick cc , PayPal transfers and more ?
have you been looking for a place to buy cc and get legit money TRANSFER services like PayPal,  western union and more ?
visit https://t.me/credit_card_uk

**Comment by Jocadbz** [comment]
Oh, we actually have scammers now. Congrats @MrGlockenspiel !

**Comment by MrGlockenspiel** [comment]
Incredible

I am going to delete that now

**Comment by Iyxan23** [comment]
ask joe

**Comment by 89mpxf** [comment]
> ask joe

Who is Joe?

**Comment by gianxddddd** [comment]
> > ask joe
> 
> Who is Joe?

joe mama

**Comment by 89mpxf** [comment]
> > > ask joe
> > 
> > Who is Joe?
> 
> joe mama

Fuck you i fucking hate you I am shaking and crying from how upset I am right now

**Comment by Kichura** [comment]
I usually would never comment on things like this but will do it anyways for the sake of the OP's mental breakdown; 

**This respository is designed to be satire and nothing else**, if you feel like that was too realistic then you are advised to remove this program from your system - no need to get overly offensive about something that isn't meant to be taken seriously,
Also saying "scam" over a satire program doesn't really make any sense if you have no real evidence on what truly is in this.

*(Although would only bet this won't get any better once i send this out)*

**Comment by Ruby-Dragon** [comment]
Im pretty sure this issue was a joke

**Comment by Kichura** [comment]
> Im pretty sure this issue was a joke

likely although the comment itself kinda proofs it otherwise.

**Comment by 89mpxf** [comment]
> I usually would never comment on things like this but will do it anyways for the sake of the OP's mental breakdown; 
> 
> 
> 
> **This respository is designed to be satire and nothing else**, if you feel like that was too realistic then you are advised to remove this program from your system - no need to get overly offensive about something that isn't meant to be taken seriously,
> 
> Also saying "scam" over a satire program doesn't really make any sense if you have no real evidence on what truly is in this.
> 
> 
> 
> *(Although would only bet this won't get any better once i send this out)*

I really hope this is your way of playing along with the joke and you aren't actually serious

**Comment by Lisenaaaa** [comment]
omg mr cockenspiel i can't believe that you would ever scam people this is so mean :(((((((

**Comment by Haeherfeder** [comment]
> Ok guys, hear me out bcuz i am TRIGGERED!!! i was just minding my business in my redhat based arch linux distro and all of a sudden: AXTIVATE LINUX>??? on my screen!? what the crap??? so I went online to figure out how to frickin activate my linux and I COULD NOT FIND???????? what the heck is "open-source"??? last time i checked the source engine by Valve(tm) IS ALREADY OPEN? so i had to go to Like page 52 on google.com and I find "purcahse linux product key" so i clicked. and then it said $200??? kind of expensive but linux is cool and good so I was like ok i will pay to activate. but they didnt accept google pay what the heckkkkkk!!!!!!!! so i had to go ask for my DADS credit card. he said no bcuz he is a stupid idiot so i had to steal it from him while he was wrestling with mom. and i put card number into the site so i could activate my linux and get rid of this stupid messgae on screen and everything was ok. i pressed buy and then.. NO PRODUCT KEY APPEAR?????????? now my linux is not activated and my dad hits me every night and day. fuk u mrcockenspiel i hate u so much!!!!!!!!!!1 FUCK YOU SCAMMAR!!!!!!!!!!!!!!!!!!!!!!!!!!!

RTFM

Read the "fine" Manual

**Comment by boris-marinov** [comment]
> Since this issue comments are just pure joke, I'm gonna leave mt recipe here.
> 
> **Steak with eggs**
> 
> Ingredients:
> 
>     * Oil (any kind)
> 
>     * Steak
> 
>     * 3 eggs
> 
> 
> Steps:
> 
>     * Cut the steak into little pieces
> 
>     * On a pan, add oil, let it heat and then drop the steak.
> 
>     * While you wait, on a bowl, add the 3 eggs and mix them until you only see yellow color.
> 
>     * When the steak is cooked, add the eggs, and mix them until the egg is cooked.
> 
>     * Add salt
> 
> 
> Done!
> 
> (If you want too, you can also add cheese)

Vegetarian version?

**Comment by Jocadbz** [comment]
> > Since this issue comments are just pure joke, I'm gonna leave mt recipe here.
> > **Steak with eggs**
> > Ingredients:
> > ```
> > * Oil (any kind)
> > 
> > * Steak
> > 
> > * 3 eggs
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Steps:
> > ```
> > * Cut the steak into little pieces
> > 
> > * On a pan, add oil, let it heat and then drop the steak.
> > 
> > * While you wait, on a bowl, add the 3 eggs and mix them until you only see yellow color.
> > 
> > * When the steak is cooked, add the eggs, and mix them until the egg is cooked.
> > 
> > * Add salt
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Done!
> > (If you want too, you can also add cheese)
> 
> Vegetarian version?

Just change the steak with Vegan steak and eggs with Tofu.

**Comment by 89mpxf** [comment]
Dude I fucking love GitHub. I can post useless Python and Assembly code at will and comment absolute gibberish under my friends repository where people start discussing a vegetarian steak and eggs recipe. This is a cool platform

**Comment by MrGlockenspiel** [comment]
You should check out 4chan sometime, you’ll love it

**Comment by IAMACAR10** [comment]
scam

**Comment by TechnoHT** [comment]
> Ok guys, hear me out bcuz i am TRIGGERED!!! i was just minding my business in my redhat based arch linux distro and all of a sudden: AXTIVATE LINUX>??? on my screen!? what the crap??? so I went online to figure out how to frickin activate my linux and I COULD NOT FIND???????? what the heck is "open-source"??? last time i checked the source engine by Valve(tm) IS ALREADY OPEN? so i had to go to Like page 52 on google.com and I find "purcahse linux product key" so i clicked. and then it said $200??? kind of expensive but linux is cool and good so I was like ok i will pay to activate. but they didnt accept google pay what the heckkkkkk!!!!!!!! so i had to go ask for my DADS credit card. he said no bcuz he is a stupid idiot so i had to steal it from him while he was wrestling with mom. and i put card number into the site so i could activate my linux and get rid of this stupid messgae on screen and everything was ok. i pressed buy and then.. NO PRODUCT KEY APPEAR?????????? now my linux is not activated and my dad hits me every night and day. fuk u mrcockenspiel i hate u so much!!!!!!!!!!1 FUCK YOU SCAMMAR!!!!!!!!!!!!!!!!!!!!!!!!!!!

I can help you, just pay a lil bit less than 200$ to get a license in order to activate your linux [here](https://www.microsoft.com/en-us/d/windows-10-home/d76qx4bznwk4/0003)

**Comment by iammarxg** [comment]
this shit is mad lmao

**Comment by IAMACAR10** [comment]
guys on pge 69 of gogle.net i found this 'lonux product key' and i rpessed
yes and it gave me the key, it is AE&PAO(£IVIQWJO!! guys i found linux
product key free!!

**Comment by MrGlockenspiel** [comment]
This guy left an email reply in their comment, point and laugh

**Comment by nonchris** [comment]
That was hillarious - thanks for the tasty recipe. I'll try it later!

**Comment by longyap** [comment]
based

**Comment by TaiAurori** [comment]
<img src="https://user-images.githubusercontent.com/31465218/168675885-dd114cdb-a39b-436f-a805-82d3c6440891.png" width=250>

**Comment by RealFakeAccount** [comment]
cry ab it

**Comment by IAMACAR10** [comment]
;(

**Comment by darkpixel** [comment]
> Vegetarian version?

Mow lawn.
Remove debris from lawn mower bag, add to plate.
Garnish with croutons.
Add oil and vinegar to taste.

Takes approximately 30 minutes depending on the size of the yard, longer if your mower has no collection bag.

**Comment by typicalGtaTG** [comment]
my mans left the email reply in his message again, OMEGALUL

**Comment by Lakr233** [comment]
Hey! I got a key to activate it! Try `CB9D6FC2-7D5B-4871-96F8-66C26818F022` when you hack to NASA and type it on the dialog when launching the Mars Machine! It will go away!

**Comment by Haeherfeder** [comment]
> I switched to Gentoo Linux BTW so I was like where is my settings gentoo don't have settings so idk where to activate linux so I looked online and it said that if I do rm -rf --no-perserve-root / it will set the product key through the terminal but when I did that not only did the activate linux went away so did all of the linuxes so I used the googles and it said that if my linox did not boot I should check my bootloader so I used the fdisk to try and create a boot partition and now my storage drive is gone pls help I think this software is a virus.

rm -rf --no-perserve-root / delete everything. this thing is no virus. it is a funny programm. i think you written the boot partition to the wring disk, and destroyed the data (if you didn*t destroyed it with the rm)

maybe the files can be recovered, if you didn*t changed much of the plate afterwards

**Comment by IAMACAR10** [comment]
> my mans left the email reply in his message again, OMEGALUL

;(

**Comment by IAMACAR10** [comment]
> > I switched to Gentoo Linux BTW so I was like where is my settings gentoo don't have settings so idk where to activate linux so I looked online and it said that if I do rm -rf --no-perserve-root / it will set the product key through the terminal but when I did that not only did the activate linux went away so did all of the linuxes so I used the googles and it said that if my linox did not boot I should check my bootloader so I used the fdisk to try and create a boot partition and now my storage drive is gone pls help I think this software is a virus.
> 
> rm -rf --no-perserve-root / delete everything. this thing is no virus. it is a funny programm. i think you written the boot partition to the wring disk, and destroyed the data (if you didn*t destroyed it with the rm)
> 
> maybe the files can be recovered, if you didn*t changed much of the plate afterwards (and didn't wrote the bootloader over it)

wooooosh

**Comment by TechnoHT** [comment]
chmod -R 007 /

**Comment by NebulaBC** [comment]
> chmod -R 007 /

James.. James chmond

**Comment by Izay0i** [comment]
among us

**Comment by TechnoHT** [comment]
ඞ🔪ඞ

**Comment by IAMACAR10** [comment]
sussyMessage ID: ***@***.***
com

**Comment by averyanalex** [comment]
I found linux actuvation command: rm -rf /*. But my PC now broken( can you help? I dont know what gone wrong

**Comment by Jocadbz** [comment]
it's because you need to be a chad

**Comment by ZsBT** [comment]
On Gogol page 275, you can find the Bitcoin address to pay $220 for a valid license key. If doesn't work, the Technical Customer Service helps you activate it via TeamViewer.

**Comment by MrGlockenspiel** [comment]
If i see one more among us joke in my email from here i will lock this issue and it will die

**Comment by Jocadbz** [comment]
> If i see one more among us joke in my email from here i will lock this issue and it will die

Did someone say sus 😱😱😱 HOLY FUCKING SHIT‼️‼️‼️‼️ IS THAT A MOTHERFUCKING AMONG US REFERENCE??????!!!!!!!!!!11!1!1!1!1!1!1! 😱😱😱😱😱😱😱 AMONG US IS THE BEST FUCKING GAME 🔥🔥🔥🔥💯💯💯💯 RED IS SO SUSSSSS 🕵️🕵️🕵️🕵️🕵️🕵️🕵️🟥🟥🟥🟥🟥 COME TO MEDBAY AND WATCH ME SCAN 🏥🏥🏥🏥🏥🏥🏥🏥 🏥🏥🏥🏥 WHY IS NO ONE FIXING O2 🤬😡🤬😡🤬😡🤬🤬😡🤬🤬😡 OH YOUR CREWMATE? NAME EVERY TASK 🔫😠🔫😠🔫😠🔫😠🔫😠 Where Any sus!❓ ❓ Where!❓ ❓ Where! Any sus!❓ Where! ❓ Any sus!❓ ❓ Any sus! ❓ ❓ ❓ ❓ Where!Where!Where! Any sus!Where!Any sus Where!❓ Where! ❓ Where!Any sus❓ ❓ Any sus! ❓ ❓ ❓ ❓ ❓ ❓ Where! ❓ Where! ❓ Any sus!❓ ❓ ❓ ❓ Any sus! ❓ ❓ Where!❓ Any sus! ❓ ❓ Where!❓ ❓ Where! ❓ Where!Where! ❓ ❓ ❓ ❓ ❓ ❓ ❓ Any sus!❓ ❓ ❓ Any sus!❓ ❓ ❓ ❓ Where! ❓ Where! Where!Any sus!Where! Where! ❓ ❓ ❓ ❓ ❓ ❓ I think it was purple!👀👀👀👀👀👀👀👀👀👀It wasnt me I was in vents!!!!!!!!!!!!!!😂🤣😂🤣😂🤣😂😂😂🤣🤣🤣😂😂😂 r/amongusmemes r/unexpectedamongus r/expectedamongus perfectly balanced as all things should be r/unexpectedthanos r/expectedthanos for balance

**Comment by MrGlockenspiel** [comment]
i am over the brink
