### ISSUE TITLE
Nonfree license cannot be enforced

### ISSUE THREAD

**Issue by TechnologyClassroom** [MrGlockenspiel/activate-linux#76]
The Based License is [nonfree](https://gitlab.alpinelinux.org/alpine/aports/-/issues/13818) and [cannot be enforced](https://github.com/ThatOneCalculator/BASED-LICENSE/issues/6).  The Based readme now says, "Warning: This license isn't legally viable as pointed out by #6 and if you're looking for a serious license, consider the (A)GPL3 or the MPL2. This was mostly written jokingly and I'm not a legal expert, please keep this in mind when using the BASED license."

If you want to build a community around this project, I would recommend switching to a different license such as GPL-3.0-or-later or AGPL-3.0-or-later.

**Comment by Ruby-Dragon** [comment]
This was entirely made as a joke and was not expected to get this much attention. That is probably a good idea

**Comment by ReperakDev** [comment]
While I agree with you on not using the "based license," I find the sources you have to be quite amusing if not laughable.

> The Based License is [nonfree](https://gitlab.alpinelinux.org/alpine/aports/-/issues/13818) [...]

This has made me lose all respect for the Alpine developers for even considering putting that in their repos.
<sup>also is that Drew DeVault??? That's unbelievable. I'll be sure to avoid Alpine from now on :laughing:</sup>

> [...] If you want to build a community around this project, I would recommend switching to a different license [...]

I can't imagine what community will form around a shitpost like this. You wouldn't be here making this issue had the Reddit users not found it.

> [...] such as GPL-3.0-or-later or AGPL-3.0-or-later.

I love the GPL, too, but I don't think that it's necessary for small programs. Even the GNU team agrees:

> It is not worth the trouble to use copyleft for most small programs. We use 300 lines as our benchmark: when a software package's source code is shorter than that, the benefits provided by copyleft are usually too small to justify the inconvenience of making sure a copy of the license always accompanies the software.

[Source](https://www.gnu.org/licenses/license-recommendations.html)

**Comment by ReperakDev** [comment]
Also, there's 15 contributors. You'd have to ask all of them to consent to a license change.

**Comment by TechnologyClassroom** [comment]
There are more than 300 lines of code in this repo.

**Comment by ReperakDev** [comment]
The 1600+ stars were accidental. Reddit is a thing, sadly.

> [...] 15 contributors would need to agree to a license change unless their commits are not copyrightable in the first place.

Does U.S. copyright grant contributors copyright to their contribution by default or is that explicit?
It seems like trying to change the license would be trickier than just leaving it.

**Comment by TechnologyClassroom** [comment]
@ReperakDev It depends on the amount of each contribution.  According to the [GNU Maintainers file](https://www.gnu.org/prep/maintain/maintain.html#Legally-Significant), "If a person contributes more than around 15 lines of code and/or text that is legally significant for copyright purposes, we need copyright papers for that contribution, as described above."

**Comment by Ruby-Dragon** [comment]
I think most if not all the contributers would agree to the licence change no questions asked

**Comment by MrGlockenspiel** [comment]
I’m okay with a relicense and I doubt anybody else would mind

**Comment by ReperakDev** [comment]
<sup>(don't provide support for void though because they're buffoons)</sup> whatcha got in mind?

**Comment by MrGlockenspiel** [comment]
https://github.com/MrGlockenspiel/activate-linux/pull/79
PR made
