### ISSUE TITLE
It may be of interest to have a link to the wallpaper

### ISSUE THREAD

**Issue by bnoctis** [MrGlockenspiel/activate-linux#81]
Which is https://unsplash.com/photos/cqbLg3lZEpk, in grayscale.

**Comment by ReperakDev** [comment]
Based and proper credit-pilled

**Comment by ReperakDev** [comment]
No I mean it's good to provide credit

**Comment by MrGlockenspiel** [comment]
https://vsthemes.org/uploads/posts/2020-04/1586853722_kurt-cotoaga-cqblg3lzepk-unsplash-modded.jpg
