### ISSUE TITLE
Error during installation on Arch Linux

### ISSUE THREAD

**Issue by pipka4** [MrGlockenspiel/activate-linux#82]
Logging into the fakeroot environment...
==> Runs package()...
install: failed stat for 'bin/activate-linux': No such file or directory
==> ERROR: Package() failed.

**Comment by ReperakDev** [comment]
More details are needed. Post full logs and makepkg.conf

**Comment by pipka4** [comment]
makepkg -s ✔ 
==> Build package activate-linux-git r70.d0d7e2c-1 (Wed May 18, 2022 21:32:13)
==> Checking dependencies to run...
==> Checking the dependencies for the build...
==> Getting the source files...
  -> Cloning the 'activate-linux' (git) repository...
Cloning to the bare repository "/home/niktia/ Downloads/activate-linux-git/activate-linux"...
remote: Enumerating objects: 405, done.
remote: Counting objects: 100% (167/167), done.
remote: Compressing objects: 100% (87/87), done.
remote: Total 405 (delta 77), reused 137 (delta 69), pack-reused 238
Receiving objects: 100% (405/405), 815.74 KiB | 82.00 KiB/s, done.
Change detection: 100% (186/186), done.
  -> Activate-linux.desktop found.
==> Checking source files using sha512sums...
    activate-linux ... Missing
    activate-linux.desktop ... Missing
==> Unpacking source files...
  -> Create a working copy of the 'activate-linux' repository (git)...
Cloning to 'activate-linux' ...
done.
==> Running pkgver()...
==> Updated version: 'activate-linux-git r102.1fd1843-1'.
==> Launches build()...
src src/activate_linux.c src/color. c -o activate-linux -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp, -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -lX11 -lXfixes -lXinerama - I/usr/include/cairo -I/usr/include/lzo -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/glib-2. 0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-4 -pthread -I/usr/include/pixman-1 -lcairo 
==> Logging into the fakeroot environment.
==> Runs package()...
install: failed stat for 'bin/activate-linux': No such file or directory
==> ERROR: Package() failed.
    Abort...

**Comment by ReperakDev** [comment]
Not entirely sure why the AUR package is looking in bin.
Anyways, the solution is the first comment in the AUR comments

**Comment by ReperakDev** [comment]
I see what's going on here. 8ff0df722f6af0f4c5fbbeaa5f88374539c384aa removed the bin/ directory and the aur package wasn't updated.

**Comment by pipka4** [comment]
I don't understand what I need to fix after reading this " 

the build no longer creates the bin folder (install: cannot stat '/bin/activate-linux': No such file or directory ). I fixed this by changing the last line of package() to: install -D activate-linux "$pkgdir/usr/bin/activate-linux"

just activate-linux instead of bin/activate-linux

and an additional error: one line before the last line: the line -Dm644 is missing a space: it should be -Dm 644.
". Can you help me with writing the command.
P.S I just recently started using Linux

**Comment by pipka4** [comment]
So I just have to wait for the update?

**Comment by er888kh** [comment]
> So I just have to wait for the update?

You can just change line 31 in PKGBUILD from:
`  install -D bin/activate-linux "$pkgdir/usr/bin/activate-linux"`
to:
`   install -D activate-linux "$pkgdir/usr/bin/activate-linux"`
(the `bin/activate-linux` part was changed to `activate-linux`)
I tried it and it worked fine

**Comment by Ruby-Dragon** [comment]
We can try to contact the maintainer of the AUR package

**Comment by EsmailELBoBDev2** [comment]
Same problem 
```yay -S activate-linux-git
:: Checking for conflicts...
:: Checking for inner conflicts...
[Aur:1]  activate-linux-git-r70.d0d7e2c-1

  1 activate-linux-git               (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
:: PKGBUILD up to date, Skipping (1/0): activate-linux-git
  1 activate-linux-git               (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
:: (1/1) Parsing SRCINFO: activate-linux-git
==> Making package: activate-linux-git r70.d0d7e2c-1 (Wed 18 May 2022 11:34:40 PM EET)
==> Retrieving sources...
  -> Updating activate-linux git repo...
Fetching origin
  -> Found activate-linux.desktop
==> Validating source files with sha512sums...
    activate-linux ... Skipped
    activate-linux.desktop ... Skipped
==> Making package: activate-linux-git r70.d0d7e2c-1 (Wed 18 May 2022 11:34:42 PM EET)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating activate-linux git repo...
Fetching origin
  -> Found activate-linux.desktop
==> Validating source files with sha512sums...
    activate-linux ... Skipped
    activate-linux.desktop ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of activate-linux git repo...
Cloning into 'activate-linux'...
done.
==> Starting pkgver()...
==> Updated version: activate-linux-git r102.1fd1843-1
==> Sources are ready.
==> Making package: activate-linux-git r102.1fd1843-1 (Wed 18 May 2022 11:34:45 PM EET)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting pkgver()...
==> Removing existing $pkgdir/ directory...
==> Starting build()...
cc src/activate_linux.c src/color.c -o activate-linux -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -lX11 -lXfixes -lXinerama  -I/usr/include/cairo -I/usr/include/lzo -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-4 -pthread -I/usr/include/pixman-1 -lcairo 
==> Entering fakeroot environment...
==> Starting package()...
install: cannot stat 'bin/activate-linux': No such file or directory
==> ERROR: A failure occurred in package().
    Aborting...
 -> error making: activate-linux-git                                                                                                           
 ```

**Comment by pipka4** [comment]
> > So I just have to wait for the update?
> 
> You can just change line 31 in PKGBUILD from: ` install -D bin/activate-linux "$pkgdir/usr/bin/activate-linux"` to: ` install -D activate-linux "$pkgdir/usr/bin/activate-linux"` (the `bin/activate-linux` part was changed to `activate-linux`) I tried it and it worked fine

It didn't work. 
activate-linux-git PKGBUILD install -D activate-linux "$pkgdir/usr/bin/activate-linux"
zsh: command not found: PKGBUILD
 ~/Z/activate-linux-git install -D activate-linux "$pkgdir/usr/bin/activate-linux"
install: failed stat for 'activate-linux': No such file or directory
 ~/Z/activate-linux-git makepkg install -D activate-linux "$pkgdir/usr/bin/activate-linux"
makepkg: Wrong parameter -- 'D'

**Comment by pipka4** [comment]
> 
Don t worked
makepkg install activate-linux "$pkgdir/usr/bin/activate-linux"
==> Build package activate-linux-git r70.d0d7e2c-1 (Thu, 19 May 2022 13:06:32)
==> Checking dependencies to run...
==> Checking the dependencies for the build...
==> Getting the source files...
  -> Cloning the 'activate-linux' (git) repository...
Cloning to the bare repository "/home/niktia/ Downloads/activate-linux-git/activate-linux"...
remote: Enumerating objects: 416, done.
remote: Counting objects: 100% (178/178), done.
remote: Compressing objects: 100% (95/95), done.
remote: Total 416 (delta 83), reused 144 (delta 72), pack-reused 238
Receiving objects: 100% (416/416), 817.42 KiB | 2.38 MiB/s, done.
Change detection: 100% (192/192), done.
  -> Activate-linux.desktop found.
==> Checking source files using sha512sums...
    activate-linux ... Missing
    activate-linux.desktop ... Missing
==> Unpacking source files...
  -> Create a working copy of the 'activate-linux' repository (git)...
Cloning to 'activate-linux' ...
done.
==> Running pkgver()...
==> Updated version: 'activate-linux-git r105.61bf1ac-1'
==> Launches build()...
src src/activate_linux.c src/color. c -o activate-linux -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp, -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -lX11 -lXfixes -lXinerama - I/usr/include/cairo -I/usr/include/lzo -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/glib-2. 0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-4 -pthread -I/usr/include/pixman-1 -lcairo 
==> Logging into the fakeroot environment.
==> Runs package()...
install: failed stat for 'bin/activate-linux': No such file or directory
==> ERROR: Package() failed.
    Abort...

**Comment by EsmailELBoBDev2** [comment]
@pipka4 they did not change aur (I think) 

you can download PKGBUILD itself and edit it https://github.com/MrGlockenspiel/activate-linux/issues/82#issuecomment-1130486601 but I was so lazy and used make

**Comment by MrGlockenspiel** [comment]
Yeah it hasn't been updated yet
For now I recommend just building from source

**Comment by Ruby-Dragon** [comment]
@MrGlockenspiel do we have a way of contacting the maintainer of the AUR package?

**Comment by MrGlockenspiel** [comment]
I can email them rq

**Comment by pipka4** [comment]
> @pipka4 they did not change aur (I think)
> 
> you can download PKGBUILD itself and edit it [#82 (comment)](https://github.com/MrGlockenspiel/activate-linux/issues/82#issuecomment-1130486601) but I was so lazy and used make

Can I use the make command?

**Comment by EsmailELBoBDev2** [comment]
> Can I use the make command?

You literally an arch user. I can't help myself but say it. RTFM -- https://github.com/MrGlockenspiel/activate-linux#building and https://github.com/MrGlockenspiel/activate-linux#other

**Comment by pipka4** [comment]
> > Can I use the make command?
> 
> You literally an arch user. I can't help myself but say it. RTFM -- https://github.com/MrGlockenspiel/activate-linux#building and https://github.com/MrGlockenspiel/activate-linux#other
That's the way it is. I have been using Linux for two weeks. But still, the commands in the post from the developer didn't help me.

make install 2 ✘ 
make: *** No rule to build target "install".  Stop.
 ~/downloads/activate-linux-git make 2 ✘ 
make: *** No targets set and no make file found.  Stop.
 ~/downloads/activate-linux-git

**Comment by ReperakDev** [comment]
Obvious troll is obvious.

**Comment by EsmailELBoBDev2** [comment]
you first run make then make install....

**Comment by EsmailELBoBDev2** [comment]
you BUILD then INSTALL

not install. wtf...

**Comment by xfnw** [comment]
> you BUILD then INSTALL

you do not actually need to, [the Makefile rule for install](https://github.com/MrGlockenspiel/activate-linux/blob/main/Makefile#L30) ensures the binary is already built, making it unnecessary to `make` before `make install`

@pipka4 was trying to run make on the aur package's repo, which did not work because it does not include a Makefile, instead of the actual source git repository

**Comment by EsmailELBoBDev2** [comment]
oh I did not notice it was aur lol

**Comment by Ruby-Dragon** [comment]
The aur still needs to be updated. We have no control over the package at the moment. I think its a bit too early to orphan it

**Comment by wuyudi** [comment]
```bash
paru -S activate-linux-git --fm=vim
```

then modify the PKGBUILD, remove the bin, as the comment in aur

https://aur.archlinux.org/packages/activate-linux-git

then it will done.

![image](https://user-images.githubusercontent.com/30024051/169691835-03f2eb1d-789a-4f7d-b001-22b7147b2cef.png)

**Comment by EsmailELBoBDev2** [comment]
Did you mean: `yay -S activate-linux-git --editor nano --answeredit a`?

You paru/vim users....

**Comment by MrGlockenspiel** [comment]
the package has been fixed so its all good now
