### ISSUE TITLE
Is it possible to update the text?

### ISSUE THREAD

**Issue by er888kh** [MrGlockenspiel/activate-linux#83]
I was thinking of modifying the code so that something like this happens:

1. Show the initial text
2. Start polling on stdin. If some input arrives (in a particular format), read it and update the text.
3. Maybe find some other function that does what `XNextEvent` does but doesn't block? Or some way to check for events using the poll itself?

But I don't know how to update the text. I tried some trivial things, but they didn't work, and I don't really have the time to go through all the manuals for the libraries used here to discover everything.

So is there an easy and elegant way to update the text?

**Comment by Ruby-Dragon** [comment]
Change what it says? Read ARGS.md

**Comment by MrGlockenspiel** [comment]
If you mean update the text while running, that would probably be a lot of changes

**Comment by MrGlockenspiel** [comment]
Gonna close this, feel free to reopen
