### ISSUE TITLE
Passing A Negative Size Value Fills The Frame Buffer With Garbage And Crashes To Login Screen Under [Ubuntu 22.04, Gnome 42 - Xorg] [Nvidia GPU]

### ISSUE THREAD

**Issue by MabelYT** [MrGlockenspiel/activate-linux#84]
Running The Command: "activate-linux -1" Will Fill The Frame Buffer With Nonsense Colors, Then Crash Your Gnome Session.

**Comment by Ruby-Dragon** [comment]
Will it actually? I dont know why it would

**Comment by MabelYT** [comment]
I've Forked The Repo, Will Make A Pull Request With A Patch.
