### ISSUE TITLE
Chinese support

### ISSUE THREAD

**Issue by Bit0r** [MrGlockenspiel/activate-linux#89]
I hope it can support Chinese. I know the corresponding code, but I don't understand how to obtain the environment language.
```c
// I didn't find an API like getlocale()
if (strcmp(getlocale(), "zh_CN") == 0) {
	title = "激活 Linux";
	subtitle = "转到“设置”以激活 Linux。";
}
```

**Comment by randomtwdude** [comment]
Traditional Chinese version:
`title = "啟用Linux"; subtitle = "移至[設定]以啟用Linux。"`

**Comment by Ruby-Dragon** [comment]
You can use the custom text i think

**Comment by BeautyYuYanli** [comment]
Hi, please check [my fork](https://github.com/BeautyYuYanli/activate-linux) if you need it.

ps. you can also specify the title & subtitle by flags. see `activate-linux -h`

**Comment by MrGlockenspiel** [comment]
This is now merged

Closing this :+1:
