### ISSUE TITLE
Add rickroll link when clicking on the main window

### ISSUE THREAD

**Issue by Jocadbz** [MrGlockenspiel/activate-linux#92]
This is a feature request:

## What I am asking
Add a function to redirect to the "Never gonna give you up" song when the user clicks on the main window

**Comment by Jocadbz** [comment]
https://www.youtube.com/watch?v=dQw4w9WgXcQ

**Comment by MrGlockenspiel** [comment]
That is far more effort than it's worth, especially for a joke

**Comment by Jocadbz** [comment]
That's sad, I'm gonna learn C and make a PR
